package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BitBitacoramantenimiento generated by hbm2java
 */
public class BitBitacoramantenimiento  implements java.io.Serializable {


     private int bitId;
     private InvDtlInventarioDetalle invDtlInventarioDetalle;
     private Date bitFechaproxima;
     private String bitComentarios;

    public BitBitacoramantenimiento() {
    }

	
    public BitBitacoramantenimiento(int bitId, InvDtlInventarioDetalle invDtlInventarioDetalle, Date bitFechaproxima) {
        this.bitId = bitId;
        this.invDtlInventarioDetalle = invDtlInventarioDetalle;
        this.bitFechaproxima = bitFechaproxima;
    }
    public BitBitacoramantenimiento(int bitId, InvDtlInventarioDetalle invDtlInventarioDetalle, Date bitFechaproxima, String bitComentarios) {
       this.bitId = bitId;
       this.invDtlInventarioDetalle = invDtlInventarioDetalle;
       this.bitFechaproxima = bitFechaproxima;
       this.bitComentarios = bitComentarios;
    }
   
    public int getBitId() {
        return this.bitId;
    }
    
    public void setBitId(int bitId) {
        this.bitId = bitId;
    }
    public InvDtlInventarioDetalle getInvDtlInventarioDetalle() {
        return this.invDtlInventarioDetalle;
    }
    
    public void setInvDtlInventarioDetalle(InvDtlInventarioDetalle invDtlInventarioDetalle) {
        this.invDtlInventarioDetalle = invDtlInventarioDetalle;
    }
    public Date getBitFechaproxima() {
        return this.bitFechaproxima;
    }
    
    public void setBitFechaproxima(Date bitFechaproxima) {
        this.bitFechaproxima = bitFechaproxima;
    }
    public String getBitComentarios() {
        return this.bitComentarios;
    }
    
    public void setBitComentarios(String bitComentarios) {
        this.bitComentarios = bitComentarios;
    }




}


