package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CatCategoriaequipo generated by hbm2java
 */
public class CatCategoriaequipo  implements java.io.Serializable {


     private int catId;
     private String catDescripcion;
     private Set solSolicituds = new HashSet(0);
     private Set equEquipos = new HashSet(0);
     private Set equEquipos_1 = new HashSet(0);

    public CatCategoriaequipo() {
    }

	
    public CatCategoriaequipo(int catId, String catDescripcion) {
        this.catId = catId;
        this.catDescripcion = catDescripcion;
    }
    public CatCategoriaequipo(int catId, String catDescripcion, Set solSolicituds, Set equEquipos, Set equEquipos_1) {
       this.catId = catId;
       this.catDescripcion = catDescripcion;
       this.solSolicituds = solSolicituds;
       this.equEquipos = equEquipos;
       this.equEquipos_1 = equEquipos_1;
    }
   
    public int getCatId() {
        return this.catId;
    }
    
    public void setCatId(int catId) {
        this.catId = catId;
    }
    public String getCatDescripcion() {
        return this.catDescripcion;
    }
    
    public void setCatDescripcion(String catDescripcion) {
        this.catDescripcion = catDescripcion;
    }
    public Set getSolSolicituds() {
        return this.solSolicituds;
    }
    
    public void setSolSolicituds(Set solSolicituds) {
        this.solSolicituds = solSolicituds;
    }
    public Set getEquEquipos() {
        return this.equEquipos;
    }
    
    public void setEquEquipos(Set equEquipos) {
        this.equEquipos = equEquipos;
    }
    public Set getEquEquipos_1() {
        return this.equEquipos_1;
    }
    
    public void setEquEquipos_1(Set equEquipos_1) {
        this.equEquipos_1 = equEquipos_1;
    }




}


