package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1



/**
 * ComCompra generated by hbm2java
 */
public class ComCompra  implements java.io.Serializable {


     private ComCompraId id;
     private InvInventario invInventario;
     private OrdOrdendecompra ordOrdendecompra;
     private int comCodFactura;
     private String comDescripcion;
     private Integer comIdIns;

    public ComCompra() {
    }

	
    public ComCompra(ComCompraId id, InvInventario invInventario, OrdOrdendecompra ordOrdendecompra, int comCodFactura) {
        this.id = id;
        this.invInventario = invInventario;
        this.ordOrdendecompra = ordOrdendecompra;
        this.comCodFactura = comCodFactura;
    }
    public ComCompra(ComCompraId id, InvInventario invInventario, OrdOrdendecompra ordOrdendecompra, int comCodFactura, String comDescripcion, Integer comIdIns) {
       this.id = id;
       this.invInventario = invInventario;
       this.ordOrdendecompra = ordOrdendecompra;
       this.comCodFactura = comCodFactura;
       this.comDescripcion = comDescripcion;
       this.comIdIns = comIdIns;
    }
   
    public ComCompraId getId() {
        return this.id;
    }
    
    public void setId(ComCompraId id) {
        this.id = id;
    }
    public InvInventario getInvInventario() {
        return this.invInventario;
    }
    
    public void setInvInventario(InvInventario invInventario) {
        this.invInventario = invInventario;
    }
    public OrdOrdendecompra getOrdOrdendecompra() {
        return this.ordOrdendecompra;
    }
    
    public void setOrdOrdendecompra(OrdOrdendecompra ordOrdendecompra) {
        this.ordOrdendecompra = ordOrdendecompra;
    }
    public int getComCodFactura() {
        return this.comCodFactura;
    }
    
    public void setComCodFactura(int comCodFactura) {
        this.comCodFactura = comCodFactura;
    }
    public String getComDescripcion() {
        return this.comDescripcion;
    }
    
    public void setComDescripcion(String comDescripcion) {
        this.comDescripcion = comDescripcion;
    }
    public Integer getComIdIns() {
        return this.comIdIns;
    }
    
    public void setComIdIns(Integer comIdIns) {
        this.comIdIns = comIdIns;
    }




}


