package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1



/**
 * ComCompraId generated by hbm2java
 */
public class ComCompraId  implements java.io.Serializable {


     private int ordId;
     private int comId;

    public ComCompraId() {
    }

    public ComCompraId(int ordId, int comId) {
       this.ordId = ordId;
       this.comId = comId;
    }
   
    public int getOrdId() {
        return this.ordId;
    }
    
    public void setOrdId(int ordId) {
        this.ordId = ordId;
    }
    public int getComId() {
        return this.comId;
    }
    
    public void setComId(int comId) {
        this.comId = comId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComCompraId) ) return false;
		 ComCompraId castOther = ( ComCompraId ) other; 
         
		 return (this.getOrdId()==castOther.getOrdId())
 && (this.getComId()==castOther.getComId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrdId();
         result = 37 * result + this.getComId();
         return result;
   }   


}


