package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * IntIinstalacion generated by hbm2java
 */
public class IntIinstalacion  implements java.io.Serializable {


     private int intId;
     private InvDtlInventarioDetalle invDtlInventarioDetalle;
     private String intDescripcion;
     private Date intFecha;

    public IntIinstalacion() {
    }

	
    public IntIinstalacion(int intId, InvDtlInventarioDetalle invDtlInventarioDetalle) {
        this.intId = intId;
        this.invDtlInventarioDetalle = invDtlInventarioDetalle;
    }
    public IntIinstalacion(int intId, InvDtlInventarioDetalle invDtlInventarioDetalle, String intDescripcion, Date intFecha) {
       this.intId = intId;
       this.invDtlInventarioDetalle = invDtlInventarioDetalle;
       this.intDescripcion = intDescripcion;
       this.intFecha = intFecha;
    }
   
    public int getIntId() {
        return this.intId;
    }
    
    public void setIntId(int intId) {
        this.intId = intId;
    }
    public InvDtlInventarioDetalle getInvDtlInventarioDetalle() {
        return this.invDtlInventarioDetalle;
    }
    
    public void setInvDtlInventarioDetalle(InvDtlInventarioDetalle invDtlInventarioDetalle) {
        this.invDtlInventarioDetalle = invDtlInventarioDetalle;
    }
    public String getIntDescripcion() {
        return this.intDescripcion;
    }
    
    public void setIntDescripcion(String intDescripcion) {
        this.intDescripcion = intDescripcion;
    }
    public Date getIntFecha() {
        return this.intFecha;
    }
    
    public void setIntFecha(Date intFecha) {
        this.intFecha = intFecha;
    }




}


