package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1



/**
 * InvDtlInventarioDetalleId generated by hbm2java
 */
public class InvDtlInventarioDetalleId  implements java.io.Serializable {


     private int insId;
     private int invId;
     private int invDtlId;

    public InvDtlInventarioDetalleId() {
    }

    public InvDtlInventarioDetalleId(int insId, int invId, int invDtlId) {
       this.insId = insId;
       this.invId = invId;
       this.invDtlId = invDtlId;
    }
   
    public int getInsId() {
        return this.insId;
    }
    
    public void setInsId(int insId) {
        this.insId = insId;
    }
    public int getInvId() {
        return this.invId;
    }
    
    public void setInvId(int invId) {
        this.invId = invId;
    }
    public int getInvDtlId() {
        return this.invDtlId;
    }
    
    public void setInvDtlId(int invDtlId) {
        this.invDtlId = invDtlId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvDtlInventarioDetalleId) ) return false;
		 InvDtlInventarioDetalleId castOther = ( InvDtlInventarioDetalleId ) other; 
         
		 return (this.getInsId()==castOther.getInsId())
 && (this.getInvId()==castOther.getInvId())
 && (this.getInvDtlId()==castOther.getInvDtlId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInsId();
         result = 37 * result + this.getInvId();
         result = 37 * result + this.getInvDtlId();
         return result;
   }   


}


