package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InvDtlInventarioDetalle generated by hbm2java
 */
public class InvDtlInventarioDetalle  implements java.io.Serializable {


     private InvDtlInventarioDetalleId id;
     private EquEquipo equEquipo;
     private InvInventario invInventario;
     private int invDtlIdEqu;
     private int invDtlCantidad;
     private String invDtlNombreEquipo;
     private Integer invDtlIdIns;
     private String invDtlCodigoinventario;
     private Set bitBitacoramantenimientos = new HashSet(0);
     private Set intIinstalacions = new HashSet(0);

    public InvDtlInventarioDetalle() {
    }

	
    public InvDtlInventarioDetalle(InvDtlInventarioDetalleId id, EquEquipo equEquipo, InvInventario invInventario, int invDtlIdEqu, int invDtlCantidad, String invDtlNombreEquipo, String invDtlCodigoinventario) {
        this.id = id;
        this.equEquipo = equEquipo;
        this.invInventario = invInventario;
        this.invDtlIdEqu = invDtlIdEqu;
        this.invDtlCantidad = invDtlCantidad;
        this.invDtlNombreEquipo = invDtlNombreEquipo;
        this.invDtlCodigoinventario = invDtlCodigoinventario;
    }
    public InvDtlInventarioDetalle(InvDtlInventarioDetalleId id, EquEquipo equEquipo, InvInventario invInventario, int invDtlIdEqu, int invDtlCantidad, String invDtlNombreEquipo, Integer invDtlIdIns, String invDtlCodigoinventario, Set bitBitacoramantenimientos, Set intIinstalacions) {
       this.id = id;
       this.equEquipo = equEquipo;
       this.invInventario = invInventario;
       this.invDtlIdEqu = invDtlIdEqu;
       this.invDtlCantidad = invDtlCantidad;
       this.invDtlNombreEquipo = invDtlNombreEquipo;
       this.invDtlIdIns = invDtlIdIns;
       this.invDtlCodigoinventario = invDtlCodigoinventario;
       this.bitBitacoramantenimientos = bitBitacoramantenimientos;
       this.intIinstalacions = intIinstalacions;
    }
   
    public InvDtlInventarioDetalleId getId() {
        return this.id;
    }
    
    public void setId(InvDtlInventarioDetalleId id) {
        this.id = id;
    }
    public EquEquipo getEquEquipo() {
        return this.equEquipo;
    }
    
    public void setEquEquipo(EquEquipo equEquipo) {
        this.equEquipo = equEquipo;
    }
    public InvInventario getInvInventario() {
        return this.invInventario;
    }
    
    public void setInvInventario(InvInventario invInventario) {
        this.invInventario = invInventario;
    }
    public int getInvDtlIdEqu() {
        return this.invDtlIdEqu;
    }
    
    public void setInvDtlIdEqu(int invDtlIdEqu) {
        this.invDtlIdEqu = invDtlIdEqu;
    }
    public int getInvDtlCantidad() {
        return this.invDtlCantidad;
    }
    
    public void setInvDtlCantidad(int invDtlCantidad) {
        this.invDtlCantidad = invDtlCantidad;
    }
    public String getInvDtlNombreEquipo() {
        return this.invDtlNombreEquipo;
    }
    
    public void setInvDtlNombreEquipo(String invDtlNombreEquipo) {
        this.invDtlNombreEquipo = invDtlNombreEquipo;
    }
    public Integer getInvDtlIdIns() {
        return this.invDtlIdIns;
    }
    
    public void setInvDtlIdIns(Integer invDtlIdIns) {
        this.invDtlIdIns = invDtlIdIns;
    }
    public String getInvDtlCodigoinventario() {
        return this.invDtlCodigoinventario;
    }
    
    public void setInvDtlCodigoinventario(String invDtlCodigoinventario) {
        this.invDtlCodigoinventario = invDtlCodigoinventario;
    }
    public Set getBitBitacoramantenimientos() {
        return this.bitBitacoramantenimientos;
    }
    
    public void setBitBitacoramantenimientos(Set bitBitacoramantenimientos) {
        this.bitBitacoramantenimientos = bitBitacoramantenimientos;
    }
    public Set getIntIinstalacions() {
        return this.intIinstalacions;
    }
    
    public void setIntIinstalacions(Set intIinstalacions) {
        this.intIinstalacions = intIinstalacions;
    }




}


