package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1



/**
 * InvInventarioId generated by hbm2java
 */
public class InvInventarioId  implements java.io.Serializable {


     private int insId;
     private int invId;

    public InvInventarioId() {
    }

    public InvInventarioId(int insId, int invId) {
       this.insId = insId;
       this.invId = invId;
    }
   
    public int getInsId() {
        return this.insId;
    }
    
    public void setInsId(int insId) {
        this.insId = insId;
    }
    public int getInvId() {
        return this.invId;
    }
    
    public void setInvId(int invId) {
        this.invId = invId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvInventarioId) ) return false;
		 InvInventarioId castOther = ( InvInventarioId ) other; 
         
		 return (this.getInsId()==castOther.getInsId())
 && (this.getInvId()==castOther.getInvId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInsId();
         result = 37 * result + this.getInvId();
         return result;
   }   


}


