package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1



/**
 * OrdDtlOrdendetalle generated by hbm2java
 */
public class OrdDtlOrdendetalle  implements java.io.Serializable {


     private OrdDtlOrdendetalleId id;
     private EquEquipo equEquipo;
     private OrdOrdendecompra ordOrdendecompra;
     private Integer ordDtlIdEqu;
     private long ordDtlPrecio;

    public OrdDtlOrdendetalle() {
    }

	
    public OrdDtlOrdendetalle(OrdDtlOrdendetalleId id, EquEquipo equEquipo, OrdOrdendecompra ordOrdendecompra, long ordDtlPrecio) {
        this.id = id;
        this.equEquipo = equEquipo;
        this.ordOrdendecompra = ordOrdendecompra;
        this.ordDtlPrecio = ordDtlPrecio;
    }
    public OrdDtlOrdendetalle(OrdDtlOrdendetalleId id, EquEquipo equEquipo, OrdOrdendecompra ordOrdendecompra, Integer ordDtlIdEqu, long ordDtlPrecio) {
       this.id = id;
       this.equEquipo = equEquipo;
       this.ordOrdendecompra = ordOrdendecompra;
       this.ordDtlIdEqu = ordDtlIdEqu;
       this.ordDtlPrecio = ordDtlPrecio;
    }
   
    public OrdDtlOrdendetalleId getId() {
        return this.id;
    }
    
    public void setId(OrdDtlOrdendetalleId id) {
        this.id = id;
    }
    public EquEquipo getEquEquipo() {
        return this.equEquipo;
    }
    
    public void setEquEquipo(EquEquipo equEquipo) {
        this.equEquipo = equEquipo;
    }
    public OrdOrdendecompra getOrdOrdendecompra() {
        return this.ordOrdendecompra;
    }
    
    public void setOrdOrdendecompra(OrdOrdendecompra ordOrdendecompra) {
        this.ordOrdendecompra = ordOrdendecompra;
    }
    public Integer getOrdDtlIdEqu() {
        return this.ordDtlIdEqu;
    }
    
    public void setOrdDtlIdEqu(Integer ordDtlIdEqu) {
        this.ordDtlIdEqu = ordDtlIdEqu;
    }
    public long getOrdDtlPrecio() {
        return this.ordDtlPrecio;
    }
    
    public void setOrdDtlPrecio(long ordDtlPrecio) {
        this.ordDtlPrecio = ordDtlPrecio;
    }




}


