package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdOrdendecompra generated by hbm2java
 */
public class OrdOrdendecompra  implements java.io.Serializable {


     private int ordId;
     private EstEstado estEstado;
     private ProProveedor proProveedor;
     private SolSolicitud solSolicitud;
     private Date ordFecha;
     private String ordDescripcion;
     private Boolean ordAprobada;
     private long ordTotal;
     private Set comCompras = new HashSet(0);
     private Set ordDtlOrdendetalles = new HashSet(0);

    public OrdOrdendecompra() {
    }

	
    public OrdOrdendecompra(int ordId, EstEstado estEstado, ProProveedor proProveedor, SolSolicitud solSolicitud, Date ordFecha, long ordTotal) {
        this.ordId = ordId;
        this.estEstado = estEstado;
        this.proProveedor = proProveedor;
        this.solSolicitud = solSolicitud;
        this.ordFecha = ordFecha;
        this.ordTotal = ordTotal;
    }
    public OrdOrdendecompra(int ordId, EstEstado estEstado, ProProveedor proProveedor, SolSolicitud solSolicitud, Date ordFecha, String ordDescripcion, Boolean ordAprobada, long ordTotal, Set comCompras, Set ordDtlOrdendetalles) {
       this.ordId = ordId;
       this.estEstado = estEstado;
       this.proProveedor = proProveedor;
       this.solSolicitud = solSolicitud;
       this.ordFecha = ordFecha;
       this.ordDescripcion = ordDescripcion;
       this.ordAprobada = ordAprobada;
       this.ordTotal = ordTotal;
       this.comCompras = comCompras;
       this.ordDtlOrdendetalles = ordDtlOrdendetalles;
    }
   
    public int getOrdId() {
        return this.ordId;
    }
    
    public void setOrdId(int ordId) {
        this.ordId = ordId;
    }
    public EstEstado getEstEstado() {
        return this.estEstado;
    }
    
    public void setEstEstado(EstEstado estEstado) {
        this.estEstado = estEstado;
    }
    public ProProveedor getProProveedor() {
        return this.proProveedor;
    }
    
    public void setProProveedor(ProProveedor proProveedor) {
        this.proProveedor = proProveedor;
    }
    public SolSolicitud getSolSolicitud() {
        return this.solSolicitud;
    }
    
    public void setSolSolicitud(SolSolicitud solSolicitud) {
        this.solSolicitud = solSolicitud;
    }
    public Date getOrdFecha() {
        return this.ordFecha;
    }
    
    public void setOrdFecha(Date ordFecha) {
        this.ordFecha = ordFecha;
    }
    public String getOrdDescripcion() {
        return this.ordDescripcion;
    }
    
    public void setOrdDescripcion(String ordDescripcion) {
        this.ordDescripcion = ordDescripcion;
    }
    public Boolean getOrdAprobada() {
        return this.ordAprobada;
    }
    
    public void setOrdAprobada(Boolean ordAprobada) {
        this.ordAprobada = ordAprobada;
    }
    public long getOrdTotal() {
        return this.ordTotal;
    }
    
    public void setOrdTotal(long ordTotal) {
        this.ordTotal = ordTotal;
    }
    public Set getComCompras() {
        return this.comCompras;
    }
    
    public void setComCompras(Set comCompras) {
        this.comCompras = comCompras;
    }
    public Set getOrdDtlOrdendetalles() {
        return this.ordDtlOrdendetalles;
    }
    
    public void setOrdDtlOrdendetalles(Set ordDtlOrdendetalles) {
        this.ordDtlOrdendetalles = ordDtlOrdendetalles;
    }




}


