package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1



/**
 * PanRolPantallasPorRoles generated by hbm2java
 */
public class PanRolPantallasPorRoles  implements java.io.Serializable {


     private int panRolId;
     private PanPantalla panPantalla;
     private PerPermisos perPermisos;
     private RolRol rolRol;

    public PanRolPantallasPorRoles() {
    }

    public PanRolPantallasPorRoles(int panRolId, PanPantalla panPantalla, PerPermisos perPermisos, RolRol rolRol) {
       this.panRolId = panRolId;
       this.panPantalla = panPantalla;
       this.perPermisos = perPermisos;
       this.rolRol = rolRol;
    }
   
    public int getPanRolId() {
        return this.panRolId;
    }
    
    public void setPanRolId(int panRolId) {
        this.panRolId = panRolId;
    }
    public PanPantalla getPanPantalla() {
        return this.panPantalla;
    }
    
    public void setPanPantalla(PanPantalla panPantalla) {
        this.panPantalla = panPantalla;
    }
    public PerPermisos getPerPermisos() {
        return this.perPermisos;
    }
    
    public void setPerPermisos(PerPermisos perPermisos) {
        this.perPermisos = perPermisos;
    }
    public RolRol getRolRol() {
        return this.rolRol;
    }
    
    public void setRolRol(RolRol rolRol) {
        this.rolRol = rolRol;
    }




}


