package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PerPermisos generated by hbm2java
 */
public class PerPermisos  implements java.io.Serializable {


     private int perId;
     private String perDescripcion;
     private Set panRolPantallasPorRoleses = new HashSet(0);

    public PerPermisos() {
    }

	
    public PerPermisos(int perId, String perDescripcion) {
        this.perId = perId;
        this.perDescripcion = perDescripcion;
    }
    public PerPermisos(int perId, String perDescripcion, Set panRolPantallasPorRoleses) {
       this.perId = perId;
       this.perDescripcion = perDescripcion;
       this.panRolPantallasPorRoleses = panRolPantallasPorRoleses;
    }
   
    public int getPerId() {
        return this.perId;
    }
    
    public void setPerId(int perId) {
        this.perId = perId;
    }
    public String getPerDescripcion() {
        return this.perDescripcion;
    }
    
    public void setPerDescripcion(String perDescripcion) {
        this.perDescripcion = perDescripcion;
    }
    public Set getPanRolPantallasPorRoleses() {
        return this.panRolPantallasPorRoleses;
    }
    
    public void setPanRolPantallasPorRoleses(Set panRolPantallasPorRoleses) {
        this.panRolPantallasPorRoleses = panRolPantallasPorRoleses;
    }




}


