package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProProveedor generated by hbm2java
 */
public class ProProveedor  implements java.io.Serializable {


     private int proId;
     private MunMunicipio munMunicipio;
     private String proNombre;
     private String proDireccion;
     private Set resRestriccions = new HashSet(0);
     private Set ordOrdendecompras = new HashSet(0);
     private Set equEquiposForProProId = new HashSet(0);
     private Set equEquiposForProProId_1 = new HashSet(0);
     private Set equEquiposForProId = new HashSet(0);
     private Set equEquiposForProId_1 = new HashSet(0);

    public ProProveedor() {
    }

	
    public ProProveedor(int proId, MunMunicipio munMunicipio, String proNombre, String proDireccion) {
        this.proId = proId;
        this.munMunicipio = munMunicipio;
        this.proNombre = proNombre;
        this.proDireccion = proDireccion;
    }
    public ProProveedor(int proId, MunMunicipio munMunicipio, String proNombre, String proDireccion, Set resRestriccions, Set ordOrdendecompras, Set equEquiposForProProId, Set equEquiposForProProId_1, Set equEquiposForProId, Set equEquiposForProId_1) {
       this.proId = proId;
       this.munMunicipio = munMunicipio;
       this.proNombre = proNombre;
       this.proDireccion = proDireccion;
       this.resRestriccions = resRestriccions;
       this.ordOrdendecompras = ordOrdendecompras;
       this.equEquiposForProProId = equEquiposForProProId;
       this.equEquiposForProProId_1 = equEquiposForProProId_1;
       this.equEquiposForProId = equEquiposForProId;
       this.equEquiposForProId_1 = equEquiposForProId_1;
    }
   
    public int getProId() {
        return this.proId;
    }
    
    public void setProId(int proId) {
        this.proId = proId;
    }
    public MunMunicipio getMunMunicipio() {
        return this.munMunicipio;
    }
    
    public void setMunMunicipio(MunMunicipio munMunicipio) {
        this.munMunicipio = munMunicipio;
    }
    public String getProNombre() {
        return this.proNombre;
    }
    
    public void setProNombre(String proNombre) {
        this.proNombre = proNombre;
    }
    public String getProDireccion() {
        return this.proDireccion;
    }
    
    public void setProDireccion(String proDireccion) {
        this.proDireccion = proDireccion;
    }
    public Set getResRestriccions() {
        return this.resRestriccions;
    }
    
    public void setResRestriccions(Set resRestriccions) {
        this.resRestriccions = resRestriccions;
    }
    public Set getOrdOrdendecompras() {
        return this.ordOrdendecompras;
    }
    
    public void setOrdOrdendecompras(Set ordOrdendecompras) {
        this.ordOrdendecompras = ordOrdendecompras;
    }
    public Set getEquEquiposForProProId() {
        return this.equEquiposForProProId;
    }
    
    public void setEquEquiposForProProId(Set equEquiposForProProId) {
        this.equEquiposForProProId = equEquiposForProProId;
    }
    public Set getEquEquiposForProProId_1() {
        return this.equEquiposForProProId_1;
    }
    
    public void setEquEquiposForProProId_1(Set equEquiposForProProId_1) {
        this.equEquiposForProProId_1 = equEquiposForProProId_1;
    }
    public Set getEquEquiposForProId() {
        return this.equEquiposForProId;
    }
    
    public void setEquEquiposForProId(Set equEquiposForProId) {
        this.equEquiposForProId = equEquiposForProId;
    }
    public Set getEquEquiposForProId_1() {
        return this.equEquiposForProId_1;
    }
    
    public void setEquEquiposForProId_1(Set equEquiposForProId_1) {
        this.equEquiposForProId_1 = equEquiposForProId_1;
    }




}


