package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RolRol generated by hbm2java
 */
public class RolRol  implements java.io.Serializable {


     private int rolId;
     private String rolDescripcion;
     private Set panRolPantallasPorRoleses = new HashSet(0);
     private Set usuRolUsuariosPorRols = new HashSet(0);

    public RolRol() {
    }

	
    public RolRol(int rolId, String rolDescripcion) {
        this.rolId = rolId;
        this.rolDescripcion = rolDescripcion;
    }
    public RolRol(int rolId, String rolDescripcion, Set panRolPantallasPorRoleses, Set usuRolUsuariosPorRols) {
       this.rolId = rolId;
       this.rolDescripcion = rolDescripcion;
       this.panRolPantallasPorRoleses = panRolPantallasPorRoleses;
       this.usuRolUsuariosPorRols = usuRolUsuariosPorRols;
    }
   
    public int getRolId() {
        return this.rolId;
    }
    
    public void setRolId(int rolId) {
        this.rolId = rolId;
    }
    public String getRolDescripcion() {
        return this.rolDescripcion;
    }
    
    public void setRolDescripcion(String rolDescripcion) {
        this.rolDescripcion = rolDescripcion;
    }
    public Set getPanRolPantallasPorRoleses() {
        return this.panRolPantallasPorRoleses;
    }
    
    public void setPanRolPantallasPorRoleses(Set panRolPantallasPorRoleses) {
        this.panRolPantallasPorRoleses = panRolPantallasPorRoleses;
    }
    public Set getUsuRolUsuariosPorRols() {
        return this.usuRolUsuariosPorRols;
    }
    
    public void setUsuRolUsuariosPorRols(Set usuRolUsuariosPorRols) {
        this.usuRolUsuariosPorRols = usuRolUsuariosPorRols;
    }




}


