package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SolSolicitud generated by hbm2java
 */
public class SolSolicitud  implements java.io.Serializable {


     private int solId;
     private CatCategoriaequipo catCategoriaequipo;
     private EstEstado estEstado;
     private TcoTipocontratacion tcoTipocontratacion;
     private UniUnidad uniUnidad;
     private Date solFecha;
     private String solDescripcion;
     private Set manSolMantenimientosolicituds = new HashSet(0);
     private Set ordOrdendecompras = new HashSet(0);
     private Set comSolComprasolicituds = new HashSet(0);

    public SolSolicitud() {
    }

	
    public SolSolicitud(int solId, CatCategoriaequipo catCategoriaequipo, EstEstado estEstado, TcoTipocontratacion tcoTipocontratacion, UniUnidad uniUnidad, Date solFecha, String solDescripcion) {
        this.solId = solId;
        this.catCategoriaequipo = catCategoriaequipo;
        this.estEstado = estEstado;
        this.tcoTipocontratacion = tcoTipocontratacion;
        this.uniUnidad = uniUnidad;
        this.solFecha = solFecha;
        this.solDescripcion = solDescripcion;
    }
    public SolSolicitud(int solId, CatCategoriaequipo catCategoriaequipo, EstEstado estEstado, TcoTipocontratacion tcoTipocontratacion, UniUnidad uniUnidad, Date solFecha, String solDescripcion, Set manSolMantenimientosolicituds, Set ordOrdendecompras, Set comSolComprasolicituds) {
       this.solId = solId;
       this.catCategoriaequipo = catCategoriaequipo;
       this.estEstado = estEstado;
       this.tcoTipocontratacion = tcoTipocontratacion;
       this.uniUnidad = uniUnidad;
       this.solFecha = solFecha;
       this.solDescripcion = solDescripcion;
       this.manSolMantenimientosolicituds = manSolMantenimientosolicituds;
       this.ordOrdendecompras = ordOrdendecompras;
       this.comSolComprasolicituds = comSolComprasolicituds;
    }
   
    public int getSolId() {
        return this.solId;
    }
    
    public void setSolId(int solId) {
        this.solId = solId;
    }
    public CatCategoriaequipo getCatCategoriaequipo() {
        return this.catCategoriaequipo;
    }
    
    public void setCatCategoriaequipo(CatCategoriaequipo catCategoriaequipo) {
        this.catCategoriaequipo = catCategoriaequipo;
    }
    public EstEstado getEstEstado() {
        return this.estEstado;
    }
    
    public void setEstEstado(EstEstado estEstado) {
        this.estEstado = estEstado;
    }
    public TcoTipocontratacion getTcoTipocontratacion() {
        return this.tcoTipocontratacion;
    }
    
    public void setTcoTipocontratacion(TcoTipocontratacion tcoTipocontratacion) {
        this.tcoTipocontratacion = tcoTipocontratacion;
    }
    public UniUnidad getUniUnidad() {
        return this.uniUnidad;
    }
    
    public void setUniUnidad(UniUnidad uniUnidad) {
        this.uniUnidad = uniUnidad;
    }
    public Date getSolFecha() {
        return this.solFecha;
    }
    
    public void setSolFecha(Date solFecha) {
        this.solFecha = solFecha;
    }
    public String getSolDescripcion() {
        return this.solDescripcion;
    }
    
    public void setSolDescripcion(String solDescripcion) {
        this.solDescripcion = solDescripcion;
    }
    public Set getManSolMantenimientosolicituds() {
        return this.manSolMantenimientosolicituds;
    }
    
    public void setManSolMantenimientosolicituds(Set manSolMantenimientosolicituds) {
        this.manSolMantenimientosolicituds = manSolMantenimientosolicituds;
    }
    public Set getOrdOrdendecompras() {
        return this.ordOrdendecompras;
    }
    
    public void setOrdOrdendecompras(Set ordOrdendecompras) {
        this.ordOrdendecompras = ordOrdendecompras;
    }
    public Set getComSolComprasolicituds() {
        return this.comSolComprasolicituds;
    }
    
    public void setComSolComprasolicituds(Set comSolComprasolicituds) {
        this.comSolComprasolicituds = comSolComprasolicituds;
    }




}


