package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TcoTipocontratacion generated by hbm2java
 */
public class TcoTipocontratacion  implements java.io.Serializable {


     private int tcoId;
     private String tcoDescripcion;
     private Set solSolicituds = new HashSet(0);

    public TcoTipocontratacion() {
    }

	
    public TcoTipocontratacion(int tcoId, String tcoDescripcion) {
        this.tcoId = tcoId;
        this.tcoDescripcion = tcoDescripcion;
    }
    public TcoTipocontratacion(int tcoId, String tcoDescripcion, Set solSolicituds) {
       this.tcoId = tcoId;
       this.tcoDescripcion = tcoDescripcion;
       this.solSolicituds = solSolicituds;
    }
   
    public int getTcoId() {
        return this.tcoId;
    }
    
    public void setTcoId(int tcoId) {
        this.tcoId = tcoId;
    }
    public String getTcoDescripcion() {
        return this.tcoDescripcion;
    }
    
    public void setTcoDescripcion(String tcoDescripcion) {
        this.tcoDescripcion = tcoDescripcion;
    }
    public Set getSolSolicituds() {
        return this.solSolicituds;
    }
    
    public void setSolSolicituds(Set solSolicituds) {
        this.solSolicituds = solSolicituds;
    }




}


