package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UniUnidad generated by hbm2java
 */
public class UniUnidad  implements java.io.Serializable {


     private int uniId;
     private InsInstitucion insInstitucion;
     private String uniNombre;
     private Set usrUniUsuariosUnidads = new HashSet(0);
     private Set solSolicituds = new HashSet(0);

    public UniUnidad() {
    }

	
    public UniUnidad(int uniId, InsInstitucion insInstitucion, String uniNombre) {
        this.uniId = uniId;
        this.insInstitucion = insInstitucion;
        this.uniNombre = uniNombre;
    }
    public UniUnidad(int uniId, InsInstitucion insInstitucion, String uniNombre, Set usrUniUsuariosUnidads, Set solSolicituds) {
       this.uniId = uniId;
       this.insInstitucion = insInstitucion;
       this.uniNombre = uniNombre;
       this.usrUniUsuariosUnidads = usrUniUsuariosUnidads;
       this.solSolicituds = solSolicituds;
    }
   
    public int getUniId() {
        return this.uniId;
    }
    
    public void setUniId(int uniId) {
        this.uniId = uniId;
    }
    public InsInstitucion getInsInstitucion() {
        return this.insInstitucion;
    }
    
    public void setInsInstitucion(InsInstitucion insInstitucion) {
        this.insInstitucion = insInstitucion;
    }
    public String getUniNombre() {
        return this.uniNombre;
    }
    
    public void setUniNombre(String uniNombre) {
        this.uniNombre = uniNombre;
    }
    public Set getUsrUniUsuariosUnidads() {
        return this.usrUniUsuariosUnidads;
    }
    
    public void setUsrUniUsuariosUnidads(Set usrUniUsuariosUnidads) {
        this.usrUniUsuariosUnidads = usrUniUsuariosUnidads;
    }
    public Set getSolSolicituds() {
        return this.solSolicituds;
    }
    
    public void setSolSolicituds(Set solSolicituds) {
        this.solSolicituds = solSolicituds;
    }




}


