package sv.edu.ues.bad115.entity;
// Generated 04-15-2017 04:24:49 PM by Hibernate Tools 4.3.1



/**
 * UsuRolUsuariosPorRol generated by hbm2java
 */
public class UsuRolUsuariosPorRol  implements java.io.Serializable {


     private int usuRolId;

     private int usu_id;
     private int rol_id;
     private RolRol rolRol;
     private UsuUsuario usuUsuario;

    public UsuRolUsuariosPorRol() {
    }

    public int getUsu_id() {
        return usu_id;
    }

    public void setUsu_id(int usu_id) {
        this.usu_id = usu_id;
    }

    public int getRol_id() {
        return rol_id;
    }

    public void setRol_id(int rol_id) {
        this.rol_id = rol_id;
    }
    public UsuRolUsuariosPorRol(int usuRolId, RolRol rolRol, UsuUsuario usuUsuario) {
       this.usuRolId = usuRolId;
       this.rolRol = rolRol;
       this.usuUsuario = usuUsuario;
    }
   
    public int getUsuRolId() {
        return this.usuRolId;
    }
    
    public void setUsuRolId(int usuRolId) {
        this.usuRolId = usuRolId;
    }
    public RolRol getRolRol() {
        return this.rolRol;
    }
    
    public void setRolRol(RolRol rolRol) {
        this.rolRol = rolRol;
    }
    public UsuUsuario getUsuUsuario() {
        return this.usuUsuario;
    }
    
    public void setUsuUsuario(UsuUsuario usuUsuario) {
        this.usuUsuario = usuUsuario;
    }




}


